version: '3'
services:
  retro:
    image: retropie
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/input:/dev/input"
      - "/dev/snd:/dev/snd"
      - "/dev/vchiq:/dev/vchiq"
    # Note: No privileged: true needed since needed devices are
    #       mapped using devices and not volume
    environment:
      - "TERM=xterm"
    entrypoint: "/usr/bin/emulationstation"
    # alternatively for testing to open a shell
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
